parameters:
    jerive_scheduler.proxy.class:     Jerive\Bundle\SchedulerBundle\Schedule\DelayedProxy
    jerive_scheduler.scheduler.class: Jerive\Bundle\SchedulerBundle\Schedule\Scheduler

services:
    jerive_scheduler.proxy:
        class: %jerive_scheduler.proxy.class%
        scope: prototype
        calls:
            - [setDoctrine, ["@doctrine"]]

    jerive_scheduler.scheduler:
        class: %jerive_scheduler.scheduler.class%
        calls:
            - [setContainer, ["@service_container"]]

    jerive_scheduler.test_service:
        class: Jerive\Bundle\SchedulerBundle\Tests\Schedule\TestScheduledService

    jerive_scheduler.sonata_admin:
        class: Jerive\Bundle\SchedulerBundle\Admin\JobAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: scheduling, label: "Jobs" }
        arguments:
            - ~
            - Jerive\Bundle\SchedulerBundle\Entity\Job
            - SonataAdminBundle:CRUD