services:
    jerive_scheduler.proxy:
        class: Jerive\Bundle\SchedulerBundle\Schedule\DelayedProxy
        scope: prototype
        calls:
            - [setDoctrine, ["@doctrine"]]

    jerive_scheduler.scheduler:
        class: Jerive\Bundle\SchedulerBundle\Schedule\Scheduler
        arguments:
            - "@doctrine.orm.entity_manager"
        calls:
            - [setContainer, ["@service_container"]]

    jerive_scheduler.test_service:
        class: Jerive\Bundle\SchedulerBundle\Tests\Schedule\TestScheduledService

    jerive_scheduler.sonata_admin:
        class: Jerive\Bundle\SchedulerBundle\Admin\JobAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: scheduling, label: "Jobs" }
        arguments:
            - ~
            - Jerive\Bundle\SchedulerBundle\Entity\Job
            - JeriveSchedulerBundle:CRUDJob